######################################################################
# Automatically generated by qmake (3.0) Thu Sep 17 17:13:29 2015
######################################################################

QT+=widgets
TEMPLATE = app
TARGET = a1
INCLUDEPATH += .

# Input
HEADERS += game.h renderer.h window.h
SOURCES += game.cpp main.cpp renderer.cpp window.cpp
