######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 17 20:30:47 2015
######################################################################

QT+=widgets
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += game.h renderer.h window.h
SOURCES += game.cpp main.cpp renderer.cpp window.cpp
